# Generated by Django 5.0.3 on 2024-04-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tasks_options_tasks_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(blank=True),
            preserve_default=False,
        ),
    ]
